// Generated by CoffeeScript 1.3.3
(function() {
  var Draft, fs, _io;

  fs = require('fs');

  _io = require('socket.io');

  Draft = (function() {

    function Draft() {}

    Draft.prototype.route = function(app, socket) {
      return app.get('/javascripts/draft-client.js', function(req, res) {
        res.header("Content-Type", "application/javascript");
        return res.end("var draftSocket = io.connect('" + socket + "'); draftSocket.on('refresh', function (data) { window.location.reload() });");
      });
    };

    Draft.prototype.listen = function(basedir, app, socket, actions) {
      var action, file, io, make_cb, rule, _results;
      io = _io.listen(app);
      this.route(app, socket);
      make_cb = function(action, data) {
        return function() {
          return io.sockets.emit(action, data);
        };
      };
      _results = [];
      for (action in actions) {
        rule = actions[action];
        _results.push((function() {
          var _i, _len, _ref, _results1;
          _ref = rule.files;
          _results1 = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            file = _ref[_i];
            _results1.push(fs.watch(basedir + file, make_cb(action, rule.data)));
          }
          return _results1;
        })());
      }
      return _results;
    };

    return Draft;

  })();

  module.exports = new Draft;

}).call(this);
