// Generated by CoffeeScript 1.3.3
(function() {
  var Draft, fs, _io;

  fs = require('fs');

  _io = require('socket.io');

  Draft = (function() {

    function Draft() {}

    Draft.prototype.listen = function(basedir, app, actions) {
      var action, file, io, k, make_cb, _results;
      io = _io.listen(app);
      _results = [];
      for (k in actions) {
        action = actions[k];
        make_cb = function(action, data) {
          return function() {
            return io.sockets.emit(action, data);
          };
        };
        _results.push((function() {
          var _i, _len, _ref, _results1;
          _ref = action.files;
          _results1 = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            file = _ref[_i];
            _results1.push(fs.watch(basedir + file, make_cb(action.action, action.data)));
          }
          return _results1;
        })());
      }
      return _results;
    };

    Draft.prototype.route = function(app) {
      return app.get('/javascripts/draft-client.js', function(req, res) {
        return res.sendfile('./node_modules/draft/lib/draft-client.js');
      });
    };

    return Draft;

  })();

  module.exports = new Draft;

}).call(this);
